// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFdiV3.Models;

#nullable disable

namespace ProyectoFdiV3.Migrations
{
    [DbContext(typeof(ProyectoFdiV3DbContext))]
    [Migration("20250225064743_UpdateRegistros4")]
    partial class UpdateRegistros4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoFdiV3.Models.Categorium", b =>
                {
                    b.Property<int>("IdCat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCat"), 1L, 1);

                    b.Property<string>("NombreCat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCat");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Club", b =>
                {
                    b.Property<int>("IdClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClub"), 1L, 1);

                    b.Property<string>("NombreClub")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClub");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.CompetenciaDeportista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompetenciaIdCom")
                        .HasColumnType("int");

                    b.Property<int>("DeportistaIdDep")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaIdCom");

                    b.HasIndex("DeportistaIdDep");

                    b.ToTable("CompetenciaDeportistas");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Competencium", b =>
                {
                    b.Property<int>("IdCom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCom"), 1L, 1);

                    b.Property<bool?>("ActivoCom")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFinCom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioCom")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCatNavigationIdCat")
                        .HasColumnType("int");

                    b.Property<int?>("IdJuez")
                        .HasColumnType("int");

                    b.Property<int?>("IdMod")
                        .HasColumnType("int");

                    b.Property<int?>("IdSede")
                        .HasColumnType("int");

                    b.Property<int?>("IdSedeNavigationIdSede")
                        .HasColumnType("int");

                    b.Property<string>("NombreCom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCom");

                    b.HasIndex("IdCatNavigationIdCat");

                    b.HasIndex("IdJuez");

                    b.HasIndex("IdMod");

                    b.HasIndex("IdSedeNavigationIdSede");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Deportistum", b =>
                {
                    b.Property<int>("IdDep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDep"), 1L, 1);

                    b.Property<bool?>("ActivoDep")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidosDep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaDep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdClub")
                        .HasColumnType("int");

                    b.Property<int?>("IdEnt")
                        .HasColumnType("int");

                    b.Property<int?>("IdGen")
                        .HasColumnType("int");

                    b.Property<int?>("IdGenNavigationIdGen")
                        .HasColumnType("int");

                    b.Property<int?>("IdProNavigationIdPro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuNavigationIdUsu")
                        .HasColumnType("int");

                    b.Property<string>("NombresDep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDep");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdEnt");

                    b.HasIndex("IdGenNavigationIdGen");

                    b.HasIndex("IdProNavigationIdPro");

                    b.HasIndex("IdUsuNavigationIdUsu");

                    b.ToTable("Deportistas");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.DetalleCompetencium", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"), 1L, 1);

                    b.Property<string>("ClasRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuartosRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdComNavigationIdCom")
                        .HasColumnType("int");

                    b.Property<string>("OctavosRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemiRes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdComNavigationIdCom");

                    b.ToTable("DetalleCompetencias");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Entrenador", b =>
                {
                    b.Property<int>("IdEnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnt"), 1L, 1);

                    b.Property<bool?>("ActivoEnt")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidosEnt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaEnt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPro")
                        .HasColumnType("int");

                    b.Property<int?>("IdProNavigationIdPro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuNavigationIdUsu")
                        .HasColumnType("int");

                    b.Property<string>("NombresEnt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnt");

                    b.HasIndex("IdProNavigationIdPro");

                    b.HasIndex("IdUsuNavigationIdUsu");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Genero", b =>
                {
                    b.Property<int>("IdGen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGen"), 1L, 1);

                    b.Property<string>("NombreGen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGen");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Juez", b =>
                {
                    b.Property<int>("IdJuez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJuez"), 1L, 1);

                    b.Property<bool?>("ActivoJuez")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidosJuez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaJuez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPro")
                        .HasColumnType("int");

                    b.Property<int?>("IdProNavigationIdPro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuNavigationIdUsu")
                        .HasColumnType("int");

                    b.Property<string>("NombresJuez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PrincipalJuez")
                        .HasColumnType("bit");

                    b.HasKey("IdJuez");

                    b.HasIndex("IdProNavigationIdPro");

                    b.HasIndex("IdUsuNavigationIdUsu");

                    b.ToTable("Jueces");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Modalidad", b =>
                {
                    b.Property<int>("IdMod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMod"), 1L, 1);

                    b.Property<string>("DescripcionMod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMod");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Provincium", b =>
                {
                    b.Property<int>("IdPro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPro"), 1L, 1);

                    b.Property<string>("NombrePro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPro");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.RegistroResultado", b =>
                {
                    b.Property<int>("IdRegistroResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistroResultado"), 1L, 1);

                    b.Property<bool>("Completado1")
                        .HasColumnType("bit");

                    b.Property<bool>("Completado2")
                        .HasColumnType("bit");

                    b.Property<bool>("Completado3")
                        .HasColumnType("bit");

                    b.Property<int?>("Etapa")
                        .HasColumnType("int");

                    b.Property<int?>("IdCom")
                        .HasColumnType("int");

                    b.Property<int?>("IdDep")
                        .HasColumnType("int");

                    b.Property<int?>("Intento1")
                        .HasColumnType("int");

                    b.Property<int?>("Intento2")
                        .HasColumnType("int");

                    b.Property<int?>("Intento3")
                        .HasColumnType("int");

                    b.Property<int>("IntentosTops")
                        .HasColumnType("int");

                    b.Property<int>("IntentosZonas")
                        .HasColumnType("int");

                    b.Property<int?>("MaxEscala1")
                        .HasColumnType("int");

                    b.Property<int?>("MaxEscala2")
                        .HasColumnType("int");

                    b.Property<int?>("MaxEscala3")
                        .HasColumnType("int");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<double>("PorcentajeAlcanzado1")
                        .HasColumnType("float");

                    b.Property<double>("PorcentajeAlcanzado2")
                        .HasColumnType("float");

                    b.Property<double>("PorcentajeAlcanzado3")
                        .HasColumnType("float");

                    b.Property<int?>("Puesto")
                        .HasColumnType("int");

                    b.Property<bool>("RegistroCompleto")
                        .HasColumnType("bit");

                    b.Property<float?>("Tiempo1")
                        .HasColumnType("real");

                    b.Property<float?>("Tiempo2")
                        .HasColumnType("real");

                    b.Property<int?>("TipoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("TopB1")
                        .HasColumnType("int");

                    b.Property<int>("TopB2")
                        .HasColumnType("int");

                    b.Property<int>("TopB3")
                        .HasColumnType("int");

                    b.Property<int>("TopB4")
                        .HasColumnType("int");

                    b.Property<int>("TotalTops")
                        .HasColumnType("int");

                    b.Property<int>("TotalZonas")
                        .HasColumnType("int");

                    b.Property<int>("UltimaPresa1")
                        .HasColumnType("int");

                    b.Property<int>("UltimaPresa2")
                        .HasColumnType("int");

                    b.Property<int>("UltimaPresa3")
                        .HasColumnType("int");

                    b.Property<int>("ZonaB1")
                        .HasColumnType("int");

                    b.Property<int>("ZonaB2")
                        .HasColumnType("int");

                    b.Property<int>("ZonaB3")
                        .HasColumnType("int");

                    b.Property<int>("ZonaB4")
                        .HasColumnType("int");

                    b.HasKey("IdRegistroResultado");

                    b.HasIndex("IdCom");

                    b.HasIndex("IdDep");

                    b.ToTable("RegistroResultados");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"), 1L, 1);

                    b.Property<string>("NombreSede")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSede");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsu"), 1L, 1);

                    b.Property<bool?>("ActivoUsu")
                        .HasColumnType("bit");

                    b.Property<string>("ClaveUsu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolesUsu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsu");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.CompetenciaDeportista", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Competencium", "Competencia")
                        .WithMany("CompetenciaDeportistas")
                        .HasForeignKey("CompetenciaIdCom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFdiV3.Models.Deportistum", "Deportista")
                        .WithMany()
                        .HasForeignKey("DeportistaIdDep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("Deportista");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Competencium", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Categorium", "IdCatNavigation")
                        .WithMany("Competencia")
                        .HasForeignKey("IdCatNavigationIdCat");

                    b.HasOne("ProyectoFdiV3.Models.Juez", "IdJuezNavigation")
                        .WithMany("Competencia")
                        .HasForeignKey("IdJuez");

                    b.HasOne("ProyectoFdiV3.Models.Modalidad", "IdModNavigation")
                        .WithMany("Competencia")
                        .HasForeignKey("IdMod");

                    b.HasOne("ProyectoFdiV3.Models.Sede", "IdSedeNavigation")
                        .WithMany("Competencias")
                        .HasForeignKey("IdSedeNavigationIdSede");

                    b.Navigation("IdCatNavigation");

                    b.Navigation("IdJuezNavigation");

                    b.Navigation("IdModNavigation");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Deportistum", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Club", "IdClubNavigation")
                        .WithMany("Deportista")
                        .HasForeignKey("IdClub");

                    b.HasOne("ProyectoFdiV3.Models.Entrenador", "IdEntNavigation")
                        .WithMany("Deportista")
                        .HasForeignKey("IdEnt");

                    b.HasOne("ProyectoFdiV3.Models.Genero", "IdGenNavigation")
                        .WithMany()
                        .HasForeignKey("IdGenNavigationIdGen");

                    b.HasOne("ProyectoFdiV3.Models.Provincium", "IdProNavigation")
                        .WithMany()
                        .HasForeignKey("IdProNavigationIdPro");

                    b.HasOne("ProyectoFdiV3.Models.Usuario", "IdUsuNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuNavigationIdUsu");

                    b.Navigation("IdClubNavigation");

                    b.Navigation("IdEntNavigation");

                    b.Navigation("IdGenNavigation");

                    b.Navigation("IdProNavigation");

                    b.Navigation("IdUsuNavigation");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.DetalleCompetencium", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Competencium", "IdComNavigation")
                        .WithMany()
                        .HasForeignKey("IdComNavigationIdCom");

                    b.Navigation("IdComNavigation");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Entrenador", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Provincium", "IdProNavigation")
                        .WithMany()
                        .HasForeignKey("IdProNavigationIdPro");

                    b.HasOne("ProyectoFdiV3.Models.Usuario", "IdUsuNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuNavigationIdUsu");

                    b.Navigation("IdProNavigation");

                    b.Navigation("IdUsuNavigation");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Juez", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Provincium", "IdProNavigation")
                        .WithMany()
                        .HasForeignKey("IdProNavigationIdPro");

                    b.HasOne("ProyectoFdiV3.Models.Usuario", "IdUsuNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuNavigationIdUsu");

                    b.Navigation("IdProNavigation");

                    b.Navigation("IdUsuNavigation");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.RegistroResultado", b =>
                {
                    b.HasOne("ProyectoFdiV3.Models.Competencium", "Competencia")
                        .WithMany("RegistrosResultados")
                        .HasForeignKey("IdCom");

                    b.HasOne("ProyectoFdiV3.Models.Deportistum", "Deportista")
                        .WithMany("RegistrosResultados")
                        .HasForeignKey("IdDep");

                    b.Navigation("Competencia");

                    b.Navigation("Deportista");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Categorium", b =>
                {
                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Club", b =>
                {
                    b.Navigation("Deportista");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Competencium", b =>
                {
                    b.Navigation("CompetenciaDeportistas");

                    b.Navigation("RegistrosResultados");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Deportistum", b =>
                {
                    b.Navigation("RegistrosResultados");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Entrenador", b =>
                {
                    b.Navigation("Deportista");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Juez", b =>
                {
                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Modalidad", b =>
                {
                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("ProyectoFdiV3.Models.Sede", b =>
                {
                    b.Navigation("Competencias");
                });
#pragma warning restore 612, 618
        }
    }
}
